production:
  adapter: postgresql
  database: quotes_production
  pool: 5
  username: postgres
  password: 123456
  host: localhost
  port: 5432

development:
  adapter: postgresql
  database: quotes_dev
  pool: 5
  username: postgres
  password: 123456
  host: localhost
  port: 5432